defaults:
  - scope:
      path: "assets"
    values:
      image: true
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
- jekyll-feed
minima:
  skin: dark
  header_pages:
    - about.md
  author:
    name: Jed Leszczynski
    email: "jedrzej.leszczynski@gmail.com"
  social_links:
    - { platform: linkedin,  user_url: "https://linkedin.com/in/jed-leszczynski" }  
